config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :rewards, only: [:index]
  namespace :admin do
    resources :users, only: [:index, :new, :create, :show, :edit, :update]
    resources :rewards, only: [:new, :create, :edit, :update, :destroy]
  end
  get "login", to: 'sessions#new'
  post "login", to: 'sessions#create'
  delete "logout", to: 'sessions#destroy'
  get '/buy', to: 'users#buy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reward.rb
class Reward < ApplicationRecord
  has_and_belongs_to_many :users

  validates :name, presence: true, uniqueness: true
  validates :cost, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :rewards

  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_secure_password
end

app/controllers/admin/rewards_controller.rb
class Admin::RewardsController < ApplicationController

  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end

  def new
    @reward = Reward.new
  end

  def create
    @reward = Reward.new(rewards_params)
    if @reward.save
      redirect_to rewards_path
    else
      redirect_to new_admin_reward_path
    end
  end

  def edit
    @reward = Reward.find(params[:id])
  end

  def update
    @reward = Reward.find(params[:id])
    @reward.update(rewards_params)

    redirect_to rewards_path
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy
    redirect_to rewards_path
  end

  private

  def rewards_params
    params.require(:reward).permit(:name, :cost)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path
    else
      redirect_to new_admin_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(points: params[:user][:points], admin: params[:user][:admin])

    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    @rewards = Reward.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    else
      redirect_to login_path
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
    @rewards = @user.rewards
    render file: "/public/404" unless current_user.id == @user.id
  end

  def buy
    reward = Reward.find(params[:reward_id])
    if user_can_buy_reward?(reward)
      current_user.rewards << reward
      points_balance = current_user.points - reward.cost
      redeemed_points = current_user.redeemed_points + reward.cost
      current_user.update_attributes(points: points_balance, redeemed_points: redeemed_points)
      redirect_to current_user
    else
      flash[:error] = "You do not have enough points to buy that"
      redirect_to rewards_path
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(points: params[:user][:points])

    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def user_can_buy_reward?(reward)
    user = current_user
    (user.points - reward.cost) >= 0
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/rewards/_form.html.erb
<%= form_for([:admin, @reward]) do |f| %>
  <div class="form_group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form_group">
    <%= f.label :cost %>
    <%= f.number_field :cost %>
  </div>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/admin/rewards/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">PointBox</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Rewards", rewards_path %></li>
        <li class="active"><%= link_to "Admin Dashboard", admin_users_path if current_user && current_user.admin? %><span class="sr-only">(current)</span></li>

      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "#{current_user.username}" %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Page", user_path(current_user) %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Login", login_path %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/admin/rewards/edit.html.erb
<h2>Edit Reward</h2>

<%= render 'form' %>

app/views/admin/rewards/new.html.erb
<h2>New Reward</h2>

<%= render 'form' %>

app/views/admin/users/_edit_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <div class="form_group">
    <%= f.label :points %>
    <%= f.number_field :points %>
  </div>
  <div class="form_group">
    <%= f.label :admin %>
    <%= f.radio_button :admin, current_user.admin? %>
  </div>

  <%= f.submit class: "btn btn-success" %>
<% end %>

app/views/admin/users/_form.html.erb
<%= form_for([:admin, @user]) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>
<% end %>

app/views/admin/users/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">PointBox</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Rewards", rewards_path %></li>
        <li class="active"><%= link_to "Admin Dashboard", admin_users_path if current_user && current_user.admin? %><span class="sr-only">(current)</span></li>

      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "#{current_user.username}" %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Page", user_path(current_user) %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Login", login_path %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/admin/users/edit.html.erb
<%= render 'edit_form' %>

app/views/admin/users/index.html.erb
<h2>Admin Dashboard</h2>

<%= button_to "Create a new user", new_admin_user_path, method: :get %>

<table class="table table-striped">
  <tr>
    <th>User</th>
    <th>Points</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.points %><%= button_to "Edit", edit_admin_user_path(user), method: :get %></td>
  </tr>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PointBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'header' %>
    <div class="container">
      <%= yield %>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

app/views/rewards/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">PointBox</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Rewards", rewards_path %><span class="sr-only">(current)</span></li>
        <li><%= link_to "Admin Dashboard", admin_users_path if current_user && current_user.admin? %></li>

      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "#{current_user.username}" %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Page", user_path(current_user) %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Login", login_path %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/rewards/index.html.erb
<h2>Rewards</h2>

<%= button_to "Create new reward", new_admin_reward_path, method: :get if current_user && current_user.admin? %>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Cost</th>
    <th>Purchase</th>
    <% if current_user && current_user.admin? %>
      <th>Edit</th>
      <th>Delete</th>
    <% end %>
  </tr>
  <% @rewards.each do |reward| %>
  <tr>
    <td><%= reward.name %></td>
    <td><%= reward.cost %></td>
    <td><%= link_to "Buy", buy_path(reward_id: reward.id), class: "btn btn-primary", method: :get %></td>
    <% if current_user && current_user.admin? %>
      <td><%= button_to "Edit", edit_admin_reward_path(id: reward.id), class: "btn btn-info", method: :get %></td>
      <td><%= button_to "Delete", admin_reward_path(id: reward.id), class: "btn btn-danger", method: :delete %></td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="form_group">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="form_group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/users/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">PointBox</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Rewards", rewards_path %></li>
        <li><%= link_to "Admin Dashboard", admin_users_path if current_user && current_user.admin? %></li>

      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "#{current_user.username}" %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Page", user_path(current_user) %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Login", login_path %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<h4>Hi, <%= current_user.username %></h4>

<p>You have <%= current_user.points %> points!</p>
<% if current_user.redeemed_points > 0 %>
  <p>You have redeemed <%= current_user.redeemed_points %> points.</p>
<% end %>

<h4>Rewards</h4>

<% @rewards.each do |reward| %>
  <div class="reward">
    <%= reward.name %>
  </div>
<% end %>

app/views/welcome/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">PointBox</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Rewards", rewards_path %></li>
        <li><%= link_to "Admin Dashboard", admin_users_path if current_user && current_user.admin? %></li>

      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "#{current_user.username}" %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Page", user_path(current_user) %></li>
              <li><%= link_to "Logout", logout_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Login", login_path, class: 'login' %></li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Welcome to PointBox</h1>
</div>